# Site settings
title: 诗宁
url: "https://magic5650.github.io/blog"    # the protocol and hostname of your site, eg. `http://zhaoyuxiang.cn/blog`
baseurl: "" # the prefix of your site uri, eg. `/bohu-jekyll-theme` or just one slash `/`
#timezone: Asia/Shanghai
description: magic5650的个人博客网站。
# Your information
email: magic5650@126.com
author: Magic #yourname #magic范
place: Guangzhou #杭州
domain: yy.com #互联网
company: 欢聚时代 #Jeeyoo
position: Service Operations #业务运维
school: bjtu.edu.cn #北京交通大学
major: Computer Science&Technology#计算机科学与技术
resume: "https://magic5650.github.io/blog"
profile: You will be the best. #
twitter_username: zyx19936688
weibo_username:  magic5650
github_username:  magic5650

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
disqus_shortname: zhaoyuxiang   
# get one: https://disqus.com/admin/signup/
# duoshuo_shortname: clark-zhao  
# get one: http://duoshuo.com/create-site/

permalink: /archivers/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 2
paginate_path: "/page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
